version: '3.7'

services:
  server:
    container_name: his_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - PORT=$PORT
    ports:
      - '9191:9191'
    depends_on:
      - 'db'
    volumes:
      - .:/server
    networks:
      - api-network
  db:
    image: mongo:latest
    container_name: his_db
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - mongodb:/data/db
    networks:
      - api-network
    ports:
      - '27017:27017'

networks:
  api-network:
    driver: bridge

volumes:
  mongodb:
